# Workflow의 이름
name: API CD

# 실행 트리거
on:
  # main에 push 될 경우 실행 (PR 후 머지되면서 push 됨)
  push:
    branches:
      - main

# 배포를 하나의 그룹으로 묶어 직렬화 시킴
concurrency:
  group: test-api-production
  # 진행되는 배포가 있을 때 새로운 배포가 추가되면 진행중인 배포 중단 최신으로 진행
  cancel-in-progress: true

# GitHub가 AWS OIDC 토큰을 발급할 수 있도록 권한 부여
permissions:
  # OIDC를 사용 쓰기 권한 -
  id-token: write
  contents: read


jobs:
  docker-build:
    # 환경 변수 설정 (Git hub 내 추가 완료)
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 의존성 캐싱
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew build

      # AWS IAM Role Assume
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::975050095892:role/github-actions-test-api-role
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Docker Buildx 설치
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # build 와 Push를 한번에 진행
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            975050095892.dkr.ecr.ap-northeast-2.amazonaws.com/test-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ESC Task Image 주소 변경
      - name: Render Amazon ECS Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: test-api
          image: 975050095892.dkr.ecr.ap-northeast-2.amazonaws.com/test-api:${{ github.sha }}

      # 변경된 이미지로 배포 진행
      - name: Deploy Amazon ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: test-api-service
          cluster: test-api-cluster
          wait-for-service-stability: true